[project]
name = "mastermind"
version = "0.1.0"
description = "Mastermind in the terminal"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
